_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "3":
                - 3
                - 8
                - 16
                - 23
                - 55
            "4": 3.9.6
            "5": 0.18.7
            "8":
                - 5
            "10":
                - 9
                - 17
            "12": 0.18.7
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 10
learning_rate:
    value: 0.001
optimizer:
    value: adam
